language: python

python:
  - "3.6"      # current default Python on Travis CI

install:
  - pip install -r requirements.txt

script:
  - sh download_speaker.sh
  - python preprocess.py --speaker_root Dataset/chem --speaker chem
  - python complete_test_generate.py -d Dataset/chem -r Dataset/chem/test_results \
